name = "admin-study-catalyst-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "fa4bce83d27f6fd19ddcafaa9402a00d"

[[d1_databases]]
binding = "DB"
database_name = "admin-study-catalyst-db"
database_id = "d9416bc4-a594-431b-94a4-cfd0ce3c7506"
migrations_dir = "src/db/migrations"

[[kv_namespaces]]
binding = "KV"
id = "1c35ee3de2cf451da71ab4136a88fa92"

[[r2_buckets]]
binding = "R2"
bucket_name = "admin-study-catalyst-assets"

[triggers]
crons = ["0 * * * *"]

[vars]
ADMIN_ORIGIN = "http://localhost:5174"
STUDENT_ORIGIN = "http://localhost:5173"
R2_ACCOUNT_ID = ""
R2_ACCESS_KEY_ID = ""
R2_SECRET_ACCESS_KEY = ""
R2_BUCKET_NAME = "admin-study-catalyst-assets"
